name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Baixa o repositório
      - uses: actions/checkout@v3

      # Gera a animação da cobra
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Rafaellaerin
          outputs: dist/github-contribution-grid-snake.svg

      # Publica o SVG no branch "output"
      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
